api:
  name: pm2appname
  packName: subschema-tools
  modName: subgraph-tools
  modVer: 0
  modCopy: true
  createFiles: true
  skipExistingFiles: false
  recreateTypeFiles: true
  recreateArgs: true
  recreateFields: true

package:
  recreate: false
  name: appname
  version: 1.0.0
  env: localhosta
  dependencies:
    - subgraph-tools: file:packages/subgraph-tools-last.tgz

ecosystem:
  recreate: false
  GRAPHQL_PATH: /graphql
  SCHEMA_CONFIG: pattern-001.yaml
  development:
    namespace: development
    NODE_ENV: development
    node_args: -r esm environment=development
    watch:
      - src/schema/types
      - src/index.js
      - packages
      - package.json
    DATABASE01_USER: DATABASE01_USER
    DATABASE01_PASS: DATABASE01_PASS
    DATABASE01_DB_NAME: DATABASE01_DB_NAME
    DATABASE01_HOST: DATABASE01_HOST
    DATABASE01_PORT: 1433
    PORT: 8080
    API_URL: http://localhost:4000/gateway



  localhost:
    namespace: localhost
    NODE_ENV: localhost
    node_args: -r esm environment=localhost
    watch:
      - src/schema/types
      - src/index.js
      - packages
      - package.json
    DATABASE01_USER: DATABASE01_USER
    DATABASE01_PASS: DATABASE01_PASS
    DATABASE01_DB_NAME: DATABASE01_DB_NAME
    DATABASE01_HOST: DATABASE01_HOST
    DATABASE01_PORT: 1433
    PORT: 8019
    API_URL: http://localhost:8019

  test:
    namespace: test
    NODE_ENV: test
    node_args: -r esm environment=test
    watch:
      - src/schema/types
      - src/index.js
      - packages
      - package.json
    DATABASE01_USER: DATABASE01_USER
    DATABASE01_PASS: DATABASE01_PASS
    DATABASE01_DB_NAME: DATABASE01_DB_NAME
    DATABASE01_HOST: DATABASE01_HOST
    DATABASE01_PORT: 1433
    PORT: 0
    API_URL: http://localhost:8019
