projects:
  - name: env
    folder_submodule: subschema-tools
    name_submodule: subgraph-tools
    folder_supermodule: superschema-tools
    name_supermodule: supergraph-tools
    folder_pack: packages

  - name: POCSUB
    mod_type: subgraph
    modVer: 1.3.7
    active_proj: false
    active_repo: false
    folder_proj: PROJ-001-SUB-SCHEMA
    folder_repo: false
    modcopy_proj: true
    modcopy_repo: false
    veradjust_proj: false
    veradjust_repo: false

  - name: POC-SUPERSCHEMA
    mod_type: subgraph
    modVer: 1.3.7
    active_proj: false
    active_repo: false
    folder_proj: PROJ-002-SUPER-SCHEMA
    folder_repo: false
    modcopy_proj: true
    modcopy_repo: false
    veradjust_proj: false
    veradjust_repo: false

  - name: CLAIM
    mod_type: subgraph
    modVer: 1.3.7
    active_proj: true
    active_repo: false
    folder_proj: PROJ-119-CLAIM
    folder_repo: POB.SRV0119
    modcopy_proj: true
    modcopy_repo: false
    veradjust_proj: false
    veradjust_repo: false

  - name: POLICY
    mod_type: subgraph
    modVer: 1.3.7
    active_proj: true
    active_repo: false
    folder_proj: PROJ-123-POLICY
    folder_repo: POB.SRV0123
    modcopy_proj: true
    modcopy_repo: false
    veradjust_proj: false
    veradjust_repo: false

  - name: CUSTOMER
    mod_type: subgraph
    modVer: 1.3.7  
    active_proj: true
    active_repo: false
    folder_proj: PROJ-130-CUSTOMER
    folder_repo: POB.SRV0130
    modcopy_proj: true
    modcopy_repo: false
    veradjust_proj: false
    veradjust_repo: false

  - name: FINANCE
    mod_type: subgraph
    modVer: 1.3.7  
    active_proj: true
    active_repo: false
    folder_proj: PROJ-133-FINANCE
    folder_repo: POB.SRV0133
    modcopy_proj: true
    modcopy_repo: false
    veradjust_proj: false
    veradjust_repo: false

  - name: DISTRIBUTION
    mod_type: subgraph
    modVer: 1.3.7  
    active_proj: true
    active_repo: false
    folder_proj: PROJ-131-DISTRIBUTION
    folder_repo: POB.SRV0131
    modcopy_proj: true
    modcopy_repo: false
    veradjust_proj: false
    veradjust_repo: false

  - name: PRODUCT
    mod_type: subgraph
    modVer: 1.3.7  
    active_proj: true
    active_repo: false
    folder_proj: PROJ-134-PRODUCT
    folder_repo: POB.SRV0134
    modcopy_proj: true
    modcopy_repo: false
    veradjust_proj: false
    veradjust_repo: false

  - name: REINSURANCE
    mod_type: subgraph
    modVer: 1.3.7    
    active_proj: true
    active_repo: false
    folder_proj: PROJ-135-REINSURANCE
    folder_repo: POB.SRV0135
    modcopy_proj: true
    modcopy_repo: false
    veradjust_proj: false
    veradjust_repo: false

  - name: GATEWAY
    mod_type: supergraph
    modVer: 1.3.7
    active_proj: true
    active_repo: false
    folder_proj: PROJ-120-GATEWAY
    folder_repo: POB.SRV0120
    modcopy_proj: true
    modcopy_repo: false
    veradjust_proj: false
    veradjust_repo: false